# Generated by Django 4.2.16 on 2024-12-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noTitle', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('general', 'General'), ('tech', 'Technology'), ('life', 'Lifestyle'), ('edu', 'Education'), ('news', 'News')], default='general', max_length=50)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='placeholder.png', upload_to='img')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('refWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.writer')),
            ],
        ),
    ]
