# Generated by Django 4.2.16 on 2024-12-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_inputchatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputchatbot',
            name='text',
        ),
        migrations.AddField(
            model_name='inputchatbot',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inputchatbot',
            name='query',
            field=models.TextField(null=True),
        ),
    ]
