# Generated by Django 4.2.16 on 2024-12-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='tokens_total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='tokens_useful',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_docs/'),
        ),
    ]
