# Generated by Django 4.2.16 on 2024-12-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('tech', 'Technology'), ('life', 'Lifestyle'), ('edu', 'Education'), ('news', 'News')], default='general', max_length=50),
        ),
    ]
