# Generated by Django 4.2.16 on 2024-12-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='all_posts',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='tokens_available',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='tokens_used',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
