# Generated by Django 4.2.16 on 2024-12-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_post_likes_post_status_writer_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='name',
            new_name='pseudo_name',
        ),
        migrations.AddField(
            model_name='writer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
