# Generated by Django 4.2.16 on 2024-12-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_writer_all_posts_alter_writer_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('no_status', 'no_status'), ('for_approval', 'for_approval'), ('approved', 'approved')], default='no_status', max_length=15),
        ),
    ]
